version: '3'

name: lottie

services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: lottie-backend
    environment:
      - PORT=${BE_PORT}
      - CONNECTION_STRING=${BE_CONNECTION_STRING}
    ports:
      - "${BE_PORT}:${BE_PORT}"
    volumes:
      - ./volumes/uploads:/app/dist/uploads
    networks:
      - lottie-network

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_APP_NAME=${FE_NEXT_PUBLIC_APP_NAME}
        - NEXT_PUBLIC_API_URL=${FE_NEXT_PUBLIC_API_URL}
    container_name: lottie-frontend
    depends_on:
      - backend
    ports:
      - "${FE_PORT}:3000"
    networks:
      - lottie-network

networks:
  lottie-network:
